name: cloudlens-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: npm

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Node Project
        run: npm run build